language: go
sudo: false

go:
  - 1.14.x
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

before_install:
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls

install:
  - # Skip

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - golint `go list ./... | grep -v /vendor/`
  - go vet ./...
  - go test -v -race ./...
  - go test -covermode=count -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
